-- Your SQL goes here
CREATE TABLE posts (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
 regulation BOOLEAN NOT NULL
);
CREATE TABLE profile(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  body VARCHAR(255) NULL,
  link TEXT NULL,
 --img,link
);
