-- Your SQL goes here
CREATE TABLE posts (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
 regulation BOOLEAN NOT NULL
);
CREATE TABLE user(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NULL,
  mail_address VARCHAR(255) NULL,
  account VARCHAR(255) NULL,
  password VARCHAR(255) NULL
);
CREATE TABLE profile(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  img VARCHAR(255) NULL,
  body TEXT NOT NULL,
 regulation BOOLEAN NOT NULL
);
